// <auto-generated />
using BULK_DOWNLOAD_CFDI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BULK_DOWNLOAD_CFDI.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20260114055126_InitDB")]
    partial class InitDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasConceptos", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<string>("ClaveProductoServicio")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)");

                    b.Property<string>("ClaveUnidad")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FacturaID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<decimal>("IEPS_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IEPS_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISR_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISR_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImporteFinal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ValorUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("FacturaID");

                    b.ToTable("CtasConceptos");
                });

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasDocsRelacionados", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<bool>("Contemplado")
                        .HasColumnType("bit");

                    b.Property<string>("FacturaPPD_ID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("FacturaPPD_UUID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("IEPS_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IEPS_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISR_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISR_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpPagado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpSaldoAnt")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ImpSaldoInsoluto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NumParcialidad")
                        .HasColumnType("int");

                    b.Property<string>("PagoID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.HasKey("ID");

                    b.HasIndex("PagoID");

                    b.ToTable("CtasDocsRelacionados");
                });

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasFacturas", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("CP_Expedicion")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("Condiciones")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Descuento")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Emitida")
                        .HasColumnType("bit");

                    b.Property<bool>("Estatus")
                        .HasColumnType("bit");

                    b.Property<bool>("Expirada")
                        .HasColumnType("bit");

                    b.Property<long>("FechaCargado")
                        .HasColumnType("bigint");

                    b.Property<long>("FechaCobroPago")
                        .HasColumnType("bigint");

                    b.Property<long>("FechaCreacion")
                        .HasColumnType("bigint");

                    b.Property<long>("FechaTimbrado")
                        .HasColumnType("bigint");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FolioInterno")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("IEPS_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IEPS_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISR_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISR_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Moneda")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("MontoPendiente")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nombre_Emisor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Nombre_Receptor")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RFC_Emisor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("RFC_Receptor")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("RegimenEmisor")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("RegimenReceptor")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SerieInterna")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Timbrada")
                        .HasColumnType("bit");

                    b.Property<decimal>("TipoCambio")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TipoComprobante")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("UsoCFDI")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<float>("Version")
                        .HasColumnType("real");

                    b.Property<decimal>("descuento_MXN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("subtotal_MXN")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("total_MXN")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.ToTable("CtasFacturas");
                });

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasPagosFactura", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("FacturaPagoID")
                        .IsRequired()
                        .HasMaxLength(36)
                        .HasColumnType("nvarchar(36)");

                    b.Property<string>("FormaPago")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<decimal>("IEPS_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IEPS_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISR_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ISR_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA_Retenido")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("IVA_Trasladado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MontoTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("NoPago")
                        .HasColumnType("int");

                    b.Property<string>("NumOperacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ID");

                    b.HasIndex("FacturaPagoID");

                    b.ToTable("CtasPagosFactura");
                });

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasConceptos", b =>
                {
                    b.HasOne("BULK_DOWNLOAD_CFDI.Models.Entities.CtasFacturas", "Factura")
                        .WithMany("Conceptos")
                        .HasForeignKey("FacturaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasDocsRelacionados", b =>
                {
                    b.HasOne("BULK_DOWNLOAD_CFDI.Models.Entities.CtasPagosFactura", "Pago")
                        .WithMany("DocsRelacionados")
                        .HasForeignKey("PagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Pago");
                });

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasPagosFactura", b =>
                {
                    b.HasOne("BULK_DOWNLOAD_CFDI.Models.Entities.CtasFacturas", "Factura")
                        .WithMany("PagosFactura")
                        .HasForeignKey("FacturaPagoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Factura");
                });

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasFacturas", b =>
                {
                    b.Navigation("Conceptos");

                    b.Navigation("PagosFactura");
                });

            modelBuilder.Entity("BULK_DOWNLOAD_CFDI.Models.Entities.CtasPagosFactura", b =>
                {
                    b.Navigation("DocsRelacionados");
                });
#pragma warning restore 612, 618
        }
    }
}
